# Generated by Django 4.1.1 on 2022-10-06 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.CharField(choices=[('Adult Men', (('polo', 'Polo'), ('sando', 'Sando'), ('short', 'Short'), ('t-shirt', 'T-shirt'), ('hoodie', 'Hoodie'))), ('Adult Women', (('t-shirt', 'T-shirt'), ('dress', 'Dress'), ('crop-top', 'Crop Top'), ('blouse', 'Blouse'), ('pants', 'Pants'), ('terno', 'Terno'), ('skirts', 'Skirts'), ('hoodie', 'Hoodie'))), ('Child Boys', (('t-shirt', 'T-shirt'), ('pants', 'Pants'), ('terno', 'Terno'))), ('Child Girls', (('t-shirt', 'T-shirt'), ('pants', 'Pants'), ('skirts', 'Skirts'), ('terno', 'Terno'), ('onesie', 'Onesie'), ('dress', 'Dress')))], max_length=20)),
            ],
        ),
    ]
