# Generated by Django 4.1.1 on 2022-10-11 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_category_item_sale_category_alter_sale_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
